# Site settings
title: DigitalTrotter
email: info@digitaltrotter.com
description: > # this means to ignore newlines until "baseurl:"
  Web Development solution using Drupal, WordPress and most popular frameworks
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://digitaltrotter.com" # the base hostname & protocol for your site
twitter_username: digitaltrotter
github_username:  

# Build settings
markdown: kramdown
